#!/bin/sh
#
# tazcraft - Minecraft server config & admin tool for SliTaz
#
# Authors: Kayam Lincoln-Vazquez, Christophe Lincoln
# Copyright (C) 2017 SliTaz GNU/Linux - BSD License
#
# TODO: add spigot support, rcon handler ?, properties settings
#
. /lib/libtaz.sh

version="1.11.2"
home="/home/minecraft"
server="$home/server"
config="$server/server.properties"
ops="$server/ops.json"
whitelist="${server}/whitelist.json"

server_jar="minecraft_server.${version}.jar"
client_jar="Minecraft.jar"
client_path="$HOME/.local/share/minecraft/$client_jar"

spigot_jar="spigot-${version}.jar"

# Java settings
java_version="8u121"
java_id="218821"
java_md5="e9e7ea248e2c4826b92b3f075a80e441"
java_tarball="jre-$java_version-linux-i586.tar.gz"

# Prefer Sun Java JRE but support system wide icedtea6-jre if installed
java="$home/jre/bin/java"
if [ ! -x "$java" ]; then
	java="/usr/bin/java"
fi

#
# Functions
#
help() {
	cat << EOT

$(colorize 032 Usage:) $(basename $0) [command|key] [value]

$(colorize 032 Commands:)

  -d  downlaod      Download the Minecraft server
  -s  start         Start your Minecraft server
  -p  play          Launch the Minecraft client
  -j  java          Install Sun Java Runtime Environment
  -k  key           Get or set a key value in server.properties
  -i  info          Display server and java information
  -m  motd          Raw display of the Message Of The Day
  -o  ops           Show server operators name
  -w  with-list     Show allowed user from white list

$(colorize 032 Options:)

  --gui             Run the server with a graphical user interface
  --mem             Set the max memory usage for Minecraft server

EOT
}

# Commands
title() {
	echo ""; colorize 032 "$@"; separator "-"
}

# Check if Java is installed
check_java() {
	if [ ! -x "$java" ]; then
		colorize 031 "Can't find Java Runtime Environment (JRE)"; return 1
	fi
}

# Change default motd
defaut_motd() {
	if [ -f "$config" ]; then
		motd=$(grep ^motd= ${config} | sed s'/motd=//')
		if [ "$motd" == "A Minecraft Server" ]; then
			sed -i s'#motd=.*#motd=\\u00A72A Tazcraft Server#' ${config}
		fi
	fi
}

# Get a key value from server config file
get_key() {
	val=$(grep ^${1}= ${config} | cut -d "=" -f 2)
	echo -n "$1"; indent 15 "= $(colorize 033 $val)"
}

#
# Commands
#
case "$1" in

	-d|downlaod)
		if [ ! -f "$server/$jar" ]; then
			echo "Downloading Minecraft..."
			
			mkdir -p ${server}
			wget --no-check-certificate \
				https://s3.amazonaws.com/Minecraft.Download/versions/${version}/minecraft_server.${version}.jar \
				-O ${server}/minecraft_server.${version}.jar
			
		else
			colorize 032 "Minecraft is already downloaded :-)"
		fi ;;
	
	-s|start)
		check_java || exit 1
		[ "$mem" ] || mem="1024"
		
		colorize 032 "Starting Minecraft server..."
		[ ! "$gui" ] && opts="nogui"
		cd ${server}
		${java} -Xmx${mem}M -Xms${mem}M -jar ${server_jar} ${opts} 
		
		newline ;;
	
	-p|play)
		if [ ! -f "$client_path" ]; then
			dest_dir="$(dirname $client_path)"
			mkdir -p ${dest_dir}
			xterm -e "wget \
				http://s3.amazonaws.com/Minecraft.Download/launcher/${client_jar} \
				-O $client_path"
		fi
		${java} -jar ${client_path} & ;;
	
	-j|java)
		if [ ! -x "$home/jre/bin/java" ]; then
			echo "Installing Java Runtime Environment ($java_version)..."
			
			# Already downloaded
			if [ ! -f "$home/$java_tarball" ]; then
				wget \
					http://javadl.oracle.com/webapps/download/AutoDL?BundleId=${java_id}_${java_md5} \
					-O ${home}/${java_tarball}
			fi
			
			echo "Extracting: ${java_tarball}..."
			tar xzf ${home}/${java_tarball} -C ${home}  || exit 1
			rm -rf jre 2>/dev/null && mv ${home}/jre*_*/ ${home}/jre
			
		else
			colorize 032 "Java Runtime Environment is installed"
			${java} -version
		fi ;;
		
	-k|key)
		key="$2"
		val="$3"
		if [ "$val" ]; then
			echo "Setting $key to: $val"
			sed -i s"/${key}=.*/${key}=${val}/" ${config}
		fi
		get_key ${key} ;;
	
	-m|motd)
		defaut_motd 
		motd=$(grep ^motd= ${config} | sed s'/motd=//')
		title "Message Of The Day (motd)"
		echo  "$motd" 
		newline ;;
	
	-o|ops)
		title "Server operators"
		fgrep name ${ops} | cut -d '"' -f 4
		newline
		colorize 033 "Config file: $ops"
		newline ;;
	
	-w|white-list)
		title "Minecraft server white list"
		
		# Display white list users or give settings info
		if [ -f "$white_list" ]; then
			users=$(wc -l < $white_list)
			cat  ${white_list}
			echo -e "\nAllowed users: $users"
		else
			get_key "white-list"
			colorize 031 "White list file is not activated $val"
		fi
		
		newline ;;
	
	-i|info)
		newline
		colorize 032 "Minecraft Server"
		echo "Version : $version"
		echo "Home    : $home"
		newline
		
		colorize 032 "Server properties"
		for var in gamemode server-port level-name difficulty max-players \
			allow-flight white-list
		do
			get_key ${var}
		done
		newline
		
		if check_java; then
			colorize 032 "Java Runtime Environment"
			echo "Path: $java"
			${java} -version #2>&1 | grep "version"
		fi
		newline ;;
	
	*) help ;;
esac
exit 0
